### DISCUSSION TITLE
TrueNAS Scale?

### DISCUSSION THREAD

**Discussion by yeeahnick** [DartSteven/Nutify#17] [Q&A]
Hello everyone,

I'm trying to get this working on TrueNAS Scale (ElectricEl 24.10), but I'm running into some issues. Before I dive deeper, has anyone successfully set this up?

Thanks

**Comment by DartSteven** [comment]
> Hello everyone,
> 
> I'm trying to get this working on TrueNAS Scale (ElectricEl 24.10), but I'm running into some issues. Before I dive deeper, has anyone successfully set this up?
> 
> Thanks

Truenas does not allow the use of docker-compose.yaml even from bash?

**Reply by yeeahnick** [reply]
I believe it does, but it still requires modifications to the YAML file. What I do is create a custom app where all the setting fields are available and enter them manually. I do this for multiple apps and never struggle like I am right now. 

Where I’m getting stuck is that the app crashes upon launch. When I look at the logs, it seems to fail to load the UPS driver due to an 'Permission Denied' type of error." I think it may have to do with the device part in the config. Not sure though.

**Comment by DartSteven** [comment]
Is as if you already have the nut service active.
Doesn't truenas by default have nut active ?

**Reply by yeeahnick** [reply]
Yes it does, there's a service for it and I can see my ups in the truenas reporting. I use to have another ups app installed from their catalog (no longer available) and it wasn't conflicting with the built-in service. Maybe the app needs something special to bypass that?

**Comment by DartSteven** [comment]
Try stopping the nut service of Truenas  just to see if Nutify works. However the problem is that you already have a nut service running and Nutify also runs a nut server and they conflict. Maybe for the next releases I can think of a bypass but it becomes complicated logic to handle.
Try : go to System -> Shell and give these commands to stop nut :

```
sudo systemctl stop nut-server
sudo systemctl stop nut-client
sudo systemctl stop nut-monitor
```

now that nut is stopped try launching nutify.

Then if you want to restart Truenas NUT (but Nutify must be stopped).:

```
sudo systemctl start nut-server
sudo systemctl start nut-client
sudo systemctl start nut-monitor
```

**Reply by yeeahnick** [reply]
I am afraid that did not resolve my problem. I guess that's a good thing for you the dev. I am probably missing something in the docker configuration.

**Comment by yeeahnick** [comment]
Logs look fine up until that point.

```
2025-03-09 21:34:08.780030+00:00[STARTUP] Starting UPS drivers...
2025-03-09 21:34:08.785733+00:00[STARTUP] Set permissions for /var/run/nut: owner=nut:nut, mode=770
2025-03-09 21:34:08.791083+00:00[STARTUP] Set permissions for /run: owner=nut:nut, mode=770
2025-03-09 21:34:08.795670+00:00[STARTUP] Cleaned up stale PID files
2025-03-09 21:34:08.833697+00:00Network UPS Tools - Generic HID driver 0.53 (2.8.2)
2025-03-09 21:34:08.833747+00:00USB communication driver (libusb 1.0) 0.47
2025-03-09 21:34:08.833697+00:00libusb1: Could not open any HID devices: insufficient permissions on everything
2025-03-09 21:34:08.833779+00:00No matching HID UPS found
2025-03-09 21:34:08.833785+00:00upsnotify: failed to notify about state 4: no notification tech defined, will not spam more about it
2025-03-09 21:34:08.834116+00:00Network UPS Tools - UPS driver controller 2.8.2
2025-03-09 21:34:08.834127+00:00Driver failed to start (exit status=1)
2025-03-09 21:34:08.838421+00:00[STARTUP] First attempt failed. Starting UPS drivers in debug mode...
2025-03-09 21:34:08.843163+00:000.000000	[D1] upsdrvctl commanding all drivers (1 found): (null)
2025-03-09 21:34:08.843195+00:000.000016	[D1] Starting UPS: pfsense_ups
2025-03-09 21:34:08.877773+00:00libusb1: Could not open any HID devices: insufficient permissions on everything
2025-03-09 21:34:08.877837+00:00No matching HID UPS found
2025-03-09 21:34:08.877782+00:00Network UPS Tools - Generic HID driver 0.53 (2.8.2)
2025-03-09 21:34:08.877934+00:00USB communication driver (libusb 1.0) 0.47
2025-03-09 21:34:08.877864+00:00upsnotify: failed to notify about state 4: no notification tech defined, will not spam more about it
2025-03-09 21:34:08.878437+00:00Network UPS Tools - UPS driver controller 2.8.2
2025-03-09 21:34:08.878443+00:000.035204	Driver failed to start (exit status=1)
2025-03-09 21:34:08.878524+00:000.035239	[D1] upsdrvctl: got some errors with preceding operations, exiting with failure now
2025-03-09 21:34:08.878551+00:000.035247	[D1] Completed the job of upsdrvctl tool, cleaning up and exiting now
2025-03-09 21:34:08.878573+00:000.035259	[D1] Completed the job of upsdrvctl tool, clean-up finished, exiting now
2025-03-09 21:34:08.887753+00:00[STARTUP] Dummy UPS fallback is disabled. Not using dummy driver.
2025-03-09 21:34:08.895039+00:00[STARTUP] ERROR: Failed to start UPS drivers after multiple attempts
2025-03-09 21:34:08.902336+00:00[STARTUP] CRITICAL ERROR: Failed to start UPS drivers
2025-03-09 21:34:08.909732+00:00[STARTUP] Failed to start NUT services
```

**Comment by yeeahnick** [comment]
As an FYI I just installed PeaNUT docker and that worked first try. I guess we can eliminate the nut service conflict.

**Reply by DartSteven** [reply]
> As an FYI I just installed PeaNUT docker and that worked first try. I guess we can eliminate the nut service conflict.

PeaNut does not use a nut server but simply uses a client. With Peanut you first need to have a nut server running otherwise it cannot connect to anything.
I could do a similar logic as well, not using the server but just the client but I would lose everything that Nutify does : real time notifications, ups states, email reports when e.g. power goes down etc..

I don't know. Maybe I'll think about it a little bit.

**Comment by yeeahnick** [comment]
Okay no worries. I guess PeaNUT will do for now, I can also intergrate it to homepage which I like. Let me know if you ever decide to go ahead with the idea. Big thanks for reaching out to me.

**Reply by DartSteven** [reply]
> Okay no worries. I guess PeaNUT will do for now, I can also intergrate it to homepage which I like. Let me know if you ever decide to go ahead with the idea. Big thanks for reaching out to me.

I got an idea: I could put a variable in the docker-compose.yaml with NUT_TYPE : SERVER/CLIENT and if you choose server then use the nut server otherwise it will auto-configure as a client also modifying upsmon to receive notifications from the remote server.
You have given me food for thought :)

**Reply by DartSteven** [reply]
> Okay no worries. I guess PeaNUT will do for now, I can also intergrate it to homepage which I like. Let me know if you ever decide to go ahead with the idea. Big thanks for reaching out to me.

Please, I made an important change.
I inserted the variable in the docker-compose.yaml of NUT_TYPE=CLIENT
Can you try configuring it this way and let me know if it works?
thanks 


in “UPS_HOST=” you need to put the ip of your server where nut server resides

```
services:
  nut:
    image: dartsteven/nutify:amd64-0.1.3TEST2Client

    container_name: Nutify-Server
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      # ===== SERVER CONFIGURATION =====
      - SERVER_NAME=UPS
      - SERVER_PORT=5050
      - SERVER_HOST=0.0.0.0
      - TIMEZONE=Europe/Rome
      - ENCRYPTION_KEY=aaaa-1234-bghy-fzwratjz-qvpy-icky-fzwr
      
      # ===== UPS CONNECTION SETTINGS =====
      - NUT_TYPE=CLIENT
      - UPS_HOST=192.168.11.10    # IP/hostname of UPS [default: localhost for local USB connection]
      - UPS_NAME=ups                                    
      - UPS_DRIVER=usbhid-ups

      - UPS_PORT=auto

      - UPS_REALPOWER_NOMINAL=1000
      
      # ===== UPS AUTHENTICATION =====
      - UPS_USER=admin
      - UPS_PASSWORD=hunter2
            
      # ===== LOGGING CONFIGURATION =====
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
      
      # ===== DUMMY UPS CONFIGURATION =====
      - USE_DUMMY_UPS=false
      - DUMMY_UPS_NAME=dummy
      - DUMMY_UPS_DRIVER=dummy-ups
      - DUMMY_UPS_PORT=dummy
      - DUMMY_UPS_DESC=Virtual UPS for testing
      
      # ===== SSL CONFIGURATION =====
      - SSL_ENABLED=false
      
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    volumes:
      - ./nut_data:/var/run/nut
      - ./nutify/logs:/app/nutify/logs
      - ./nutify/instance:/app/nutify/instance
      - ./ssl:/app/ssl
    restart: always
    user: root
```

**Reply by yeeahnick** [reply]
This works wonderfully! Good job =)

**Comment by DartSteven** [comment]
Wow!!!
Can I ask you a favor? 
Can you write or make a screen of how you configured truenas so that if other people have problems they can see how you did it? And could you write in compatibility your ups?

Thank you

**Reply by yeeahnick** [reply]
I certainly can do that for you. I will post my UPS compatibility now and will write something up for TrueNAS sometime tonight or tomorrow. Where shall I post the TrueNAS documentation once its ready?

**Comment by DartSteven** [comment]
Start here a new discussion like how to config truenas for Nutify ;)

**Comment by yeeahnick** [comment]
@DartSteven 

Hey there, I see that you added the NUT_TYPE functionality to the amd64-latest (0.1.3) image but my docker started to crash again. Had to go back to the amd64-0.1.3TEST2Client image.

**Reply by yeeahnick** [reply]
I just realized that the amd64-latest was still using version 0.1.2. The issue was on my end, as I had previously used the amd64-0.1.3TEST2Client image. To fix this, I set the option to 'always pull an image even if it is present on the host,' which allowed amd64-latest to pull version 0.1.3. Afterward, I reverted the setting to 'pull the image only if it is not already present on the host.'

![image](https://github.com/user-attachments/assets/8ee93867-6a55-40d0-8269-2e54b0c2cb8e)

**Comment by mregni** [comment]
I'm running FreeNAS as well and wanted to add my config (for documentation) as well.

docker compose file:
```
services:
  nutify:
    image: dartsteven/nutify:amd64-0.1.5
    container_name: nutify
    restart: unless-stopped
    environment:
      SERVER_NAME: UPS-Remote
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5050
      TIMEZONE: Europe/Brussels
      ENCRYPTION_KEY: NYiVfwMh7WzBcDUuZye
      NUT_TYPE: CLIENT
      UPS_HOST: 192.168.72.28
      UPS_NAME: ups
      UPS_USER: upsmon
      LOG: true
    ports:
      - 5050:5050
    volumes:
      - ./nutify/data:/var/run/nut
      - ./nutifynutify/logs:/app/nutify/logs
      - ./nutifynutify/instance:/app/nutify/instance
```

| Env vars      | Value      |
| ------------- | ------------- |
| UPS_NAME  | Identifier from FreeNAS |
| UPS_USER | User from FreeNAS (default upsmon) |
| UPS_PASSWORD  | Not needed |
| UPS_HOST | IP of FreeNAS server |
| NUT_TYPE | CLIENT |

FreeNAS config:
System -> Services -> UPS -> Edit (check the service is also running ofc)

Select correct driver (I'm using SNMP here and set IP of UPS)
Enable remote monitor!

![image](https://github.com/user-attachments/assets/eea39af3-b99e-4d00-ba11-baac7f42eee5)

If you go to reporting -> UPS you should see some data already (otherwise the connection between FreeNAS and UPS is not working)

After that you get this in Nutify:
![image](https://github.com/user-attachments/assets/b7b9b9b7-8d94-45f0-b597-0c6c692e7c43)

There are some strange things going on with the graphs, but I will make a separate issue for that.
