### DISCUSSION TITLE
widget for Homepage

### DISCUSSION THREAD

**Discussion by ercflemng** [DartSteven/Nutify#19] [Q&A] [answered]
Has anyone been able to get a Homepage widget working for Nutify? I've spent a couple of hours trying to get this to work without any luck. This is what I came up with following the Homepage documentation:

![image](https://github.com/user-attachments/assets/37939f55-ff28-459e-a977-8300f3932e29)

Any assistance would be appreciated!

**Comment by DartSteven** [comment]
Wow, just yesterday I wanted to make the homepage widget too but then I got stuck doing fixes :/ and didn't have time.

This you write “key: mysupersecretapikey” the key what are you referring to? if it's the one you put in the docker-compose.yaml in “ENCRYPTION_KEY= ” this is used to encrypt mail passwords in the database

**Reply by drewstopherlee** [reply]
Is there a single endpoint that exposes all of the API data? as I believe that's what's needed for the Custom API widget to work. I can get one data field to populate, but I can't point the widget at a second endpoint URL to get anything else.

**Comment by drewstopherlee** [comment]
@ercflemng can you share that in a code block? I can help you clean it up and get it working if you'd like.

**Reply by drewstopherlee** [reply]
scratch that, here's what I came up with:

EDIT: see [below](https://github.com/DartSteven/Nutify/discussions/19#discussioncomment-12455382)

**Comment by DartSteven** [comment]
U can try with /api/data/all

If you need I can make you a list of all the api there are Nutify

**Reply by drewstopherlee** [reply]
I actually think that's exactly what I needed, thank you! I was looking at all the different endpoints on the API page of the web UI.

**Comment by drewstopherlee** [comment, marked as answer]
@ercflemng try this:
```yaml
    - NUTify:
        href: http://192.168.0.5:5050/
        widget:
          type: customapi
          url: http://192.168.0.5:5050/api/data/all
          refreshInterval: 5000
          method: GET
          mappings:
            - field:
                data: ups_status
              label: UPS Status
              format: text
              remap:
                - value: OL
                  to: On Line
                - value: OB
                  to: On Battery
                - value: LB
                  to: Low Battery
                - value: HB
                  to: High Battery
                - value: RB
                  to: REPLACE BATTERY!
                - value: CHRG
                  to: Charging...
                - value: DISCHRG
                  to: Discharging...
                - value: BYPASS
                  to: Bypass Active
                - value: CAL
                  to: Calibrating...
                - value: OFF
                  to: Offline
                - value: OVER
                  to: OVERLOADED!
                - value: TRIM
                  to: Trimming Voltage
                - value: BOOST
                  to: Boosting Voltage
                - value: FSD
                  to: Forced Shutdown
            - field:
                data: battery_charge
              label: Battery Charge
              format: percent
            - field:
                data: ups_load
              label: System Load
              format: percent
            - field: 
                data: ups_realpower
              label: Power Usage
              format: number
              suffix: "W"
```

![Screenshot 2025-03-10 192749](https://github.com/user-attachments/assets/24577cf5-7ad6-4cdb-b778-b855372b5d98)

Note that this doesn't handle multiple UPS status messages—for me, it still shows "OL LB" instead of the remappings I added. Please let me know if this works for you and if the remappings work with a single status message. :)
