### DISCUSSION TITLE
Homepage Widget for NUTify

### DISCUSSION THREAD

**Discussion by drewstopherlee** [DartSteven/Nutify#22] [General]
If anyone else runs [Homepage](https://gethomepage.dev/) and is interested in adding a widget to display some data about the UPS, I'll post my config here. Add everything from `widget:` down to your existing entry for NUTify in your homepage [services.yaml](https://gethomepage.dev/configs/services/) file. 

**Don't forget to update the `url:` IP address and port to match your installation!**

```yaml
- Example Section:
    - NUTify:
        href: http://10.0.0.91:5050/
        widget:
          type: customapi # Defines widget type per https://gethomepage.dev/widgets/services/customapi/
          url: http://10.0.0.91:5050/api/data/all # API endpoint for NUTify (change this to match your NUTify instance)
          refreshInterval: 5000 # Refresh every 5 seconds
          method: GET
          mappings:
            - field: # Get UPS status from NUTify (see https://networkupstools.org/docs/developer-guide.chunked/new-drivers.html#_status_data for an explanation of what these mean)
                data: ups_status
              label: UPS Status
              format: text #Display the API data as text
            - field:
                data: battery_charge # Get battery percentage from NUTify
              label: Battery Charge
              format: percent # and display it as a percent
            - field:
                data: ups_load # Get system load
              label: System Load
              format: percent # Also displayed as a percent
            - field: 
                data: ups_realpower # Get the power usage of the UPS
              label: Power Usage
              format: number # Display it as a number
              suffix: "W" # And add a W at the end to signify Watts
```
And here's what it should look like:
![Screenshot 2025-03-10 192749](https://github.com/user-attachments/assets/6d692e34-28dd-410a-ba66-36edf6065c84)

If anyone has suggestions or is interested in other stats being displayed, please let me know and I can rework this config. Thanks! :D
EDIT: Also if anyone is more familiar with React/JS than I am and would like to tackle a [custom widget to be integrated into Homepage](https://gethomepage.dev/widgets/authoring/tutorial/), I'm sure @DartSteven wouldn't mind ;)

**Comment by DartSteven** [comment]
Great job, thank you very much!

<img width="1501" alt="Nutify" src="https://github.com/user-attachments/assets/cbb92b87-c851-483e-b63e-27b500e2975a" />

**Reply by drewstopherlee** [reply]
Did you use the remapping that I had in the other discussion thread? I didn't add them here because it didn't work correctly for @ercflemng or I.

**Reply by yeeahnick** [reply]
Remapping worked for me. 

```
            mappings:
            - field: # Get UPS status from NUTify 
                data: ups_status
              label: UPS Status
              format: text #Display the API data as text
              remap:
                - value: OL
                  to: Online
```

![image](https://github.com/user-attachments/assets/cd6666c8-2ce6-41b4-b8f7-902e87813e5d)
