### DISCUSSION TITLE
🧪 Nutify - [ 0.1.6/0.1.7.x ] Collaborative testing and development.

### DISCUSSION THREAD

**Discussion by DartSteven** [DartSteven/Nutify#42] [Announcements]
Hi everyone!!!

I'm actively working on **Nutify** and I would need your help to test some features, so as to ensure greater compatibility and stability across multiple environments.

In my local setup, with my two UPSs, everything works perfectly according to my requirements. But because of this, I am at risk of not noticing any bugs or problems that might arise in other scenarios.

## 🔄 What do I propose?

I would like to post **test versions** here, gather feedback and guidance on what to test, so that I can correct any problems before merging on the `master` branch with the stable version.

If everything works correctly for you too, then I can proceed with more confidence!

## 🆕 First feature to test. It will be ready soon.

<div align="center">

  <img width="500" alt="Screenshot" src="https://github.com/user-attachments/assets/3bca2000-4cff-4cf1-954a-1db33930a54d" />

  <img width="500" alt="Screenshot" src="https://github.com/user-attachments/assets/a3be94f8-9a4f-4234-ae58-1791be815db1" />

  <img width="500" alt="Screenshot" src="https://github.com/user-attachments/assets/4fa571a8-79a1-4c0c-a1e6-a4b34f42e793" />

  <img width="500" alt="Screenshot" src="https://github.com/user-attachments/assets/a56ad0a0-6b7a-4f3c-8270-dd39550d9683" />

  <img width="500" alt="Screenshot" src="https://github.com/user-attachments/assets/ee091234-75a8-47a3-abfb-cb4762168965" />

</div>

The first new feature I am working on is a **complete overhaul of the Docker container boot system**:

- NUT **will no longer be configured via `docker-compose`**.
- On first startup, the user will be **automatically redirected to a welcome page** where they can configure everything via web interface

This new mode will greatly simplify the user experience, especially for those who do not want to edit files manually.

---

Anyone who feels like helping me out with testing is welcome! 💪  

If anyone is willing to help me test these features, could you please let me know in the comments below so I can get in touch with you directly?

Feel free to write me in the comments or open an issue with feedback.

Thanks in advance to everyone!

**Comment by DartSteven** [comment]
```
ARM64 : dartsteven/test:arm64-0.1.6TEST1
AMD64 : dartsteven/test:amd64-0.1.6TEST1
```

New docker-compose.yaml :

```
services:
  nut:
    image: dartsteven/test:amd64-0.1.6TEST1  # or dartsteven/test:arm64-0.1.6TEST1
    container_name: Nutify
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
      - SSL_ENABLED=true
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    volumes:
      - ./Nutify/logs:/app/nutify/logs
      - ./Nutify/instance:/app/nutify/instance
      - ./Nutify/ssl:/app/ssl
      - ./Nutify/etc/nut:/etc/nut
    restart: always
    user: root
```

I’ve published the two images for testing. If anyone is willing to help verify that everything works correctly, I’d really appreciate it. Otherwise, I’ll go ahead and merge to master in a couple of days. Thanks, everyone!

**Comment by DartSteven** [comment]
## 🚀 Here we go with the second test!

```
AMD64 : dartsteven/test:amd64-0.1.6TEST2
AMD64 : dartsteven/test:arm64-0.1.6TEST2
```

I'm asking for your help to test the following new features:

- 📧 **Amazon SES provider support** (for those using it)
<img width="500" alt="Amazon_SES" src="https://github.com/user-attachments/assets/84b814b0-d8d6-4664-9757-043d76000219" />



- 📥 **Download JSON button**, now available under *Advanced Options*
<img width="500" alt="Json_Download" src="https://github.com/user-attachments/assets/28e73abf-3ac6-410f-ae94-6749e5d50ce4" />


- ⚙️ **Initial configuration variables section** under *Advanced Options*
<img width="500" alt="option_setup_variable" src="https://github.com/user-attachments/assets/7f6f2f30-f0f2-4f1c-9763-55fd9e924c56" />


- 🔗 **Webhook** feature now extended with **Discord** support
<img width="500" alt="Webhook" src="https://github.com/user-attachments/assets/939296d8-bfb7-49d7-8ea1-bed68a6c96ae" />


- 🖥️ **Mini system monitor widget** to keep an eye on CPU and RAM usage
<img width="166" alt="widget_cpu_ram" src="https://github.com/user-attachments/assets/008159f3-cc09-45b9-a179-875ed7f8033f" />

- 🚨 **Alert modal** in case of connection loss with the database or other critical events
<img width="500" alt="Modal_lert" src="https://github.com/user-attachments/assets/4e0d2112-c6f4-4fa8-85c0-d8218ec001fe" />



- 🛑 **Polling auto-stop mechanism**: now the system detects anomalies when UPS becomes unreachable and stops polling to prevent weird behavior


---
- ** docker-cmpose.yaml

```
services:
  nut:
    image: dartsteven/test:amd64-0.1.6TEST2 
    container_name: Nutify
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
      - SSL_ENABLED=true
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    volumes:
      - ./Nutify/logs:/app/nutify/logs
      - ./Nutify/instance:/app/nutify/instance
      - ./Nutify/ssl:/app/ssl
      - ./Nutify/etc/nut:/etc/nut
    restart: always
    user: root
```


---

⚠️ **Reminder**:  
This is a **TEST version**, please **run it separately** from your main installation to avoid compromising your data.  
👉 **Stop your current Nutify instance before starting this one.**

🗃️ You *can* reuse your previous database, but you'll **need to reconfigure the email settings manually**.

🔐 **Note**:  
In this version, the **Encryption Key** must be entered manually in the web interface. This is **temporary** — I’ve already decided that in the **next (and final) pre-release** before the official publication on the master branch, the key will be injected via `docker-compose`.

---

🧪 Please **test all sections thoroughly**, not just the new features!  
🐞 If you find any bugs, **report them in the `BUG` section**, not here.  
I'd like to keep this thread clean for **TEST release announcements only**.

🙏 Thanks everyone for your time and help!

**Comment by DartSteven** [comment]
new version TEST3
I added an additional check to change the usb permissions.

```
dartsteven/test:amd64-0.1.6TEST3
dartsteven/test:arm64-0.1.6TEST3
```

**Comment by DartSteven** [comment]
OK Guys, 

this is it! **_RC01_** ready with all the things I needed to do. 
Please test it thoroughly, through and through. 
Please run Nutify without any other Nutify instances, and in an empty directory with exactly this docker composer . 

Tell me what you think and if you find any other bugs (hopefully not) 🙂


```
services:
  nut:
#    build: .
    image: dartsteven/test:amd64-0.1.6RC01
    container_name: Nutify
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    volumes:
      - ./Nutify/logs:/app/nutify/logs
      - ./Nutify/instance:/app/nutify/instance
      - ./Nutify/ssl:/app/ssl
      - ./Nutify/etc/nut:/etc/nut
      - /dev:/dev:rw              # Full /dev access improves hotplug handling
      - /run/udev:/run/udev:ro    # Access to udev events
    environment:
      # ===== SERVER CONFIGURATION =====
      - SERVER_PORT=5050
      - SERVER_HOST=0.0.0.0
      # ===== LOGGING CONFIGURATION =====
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
      - SSL_ENABLED=false
      - SECRET_KEY=test1234567890 # for password encryption and decryption in the database
      - UDEV=1                    # Improve USB detection
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    restart: always
    user: root
```

⚠️ Reminder:
This is a TEST version, please run it separately from your main installation to avoid compromising your data.

👉 Stop your current Nutify instance before starting this one.

🧪 Please test all sections thoroughly, not just the new features!

🐞 If you find any bugs, report them in the BUG section, not here.

I'd like to keep this thread clean for TEST release announcements only.

🙏 Thanks everyone for your time and help!
