### ISSUE TITLE
Web Interface Not Accessible

### ISSUE THREAD

**Issue by utlilb** [DartSteven/Nutify#20]
No matter what I do I can't seem to access the web interface. Logs show "[STARTUP] Web app process is running, assuming port 5050 is available" but then about 20 lines later shows "[STARTUP] No service listening on port 5050"

**Comment by utlilb** [comment]
I'm running it under docker on a linux host. See attached logs. Here is my compose file. 

  nut:
    image: dartsteven/nutify:amd64-latest
    container_name: nutify
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - NUT_TYPE=SERVER                           # Run full NUT server with drivers (default)
      - SERVER_NAME=Nutify
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=${NUT_PORT_5050}
      - TIMEZONE=${TZ}
      - ENCRYPTION_KEY=${NUT_ENC_KEY} # REQUIRED: Secret key for data encryption (32+ chars)
      - UPS_NAME=ups
      - UPS_DRIVER=usbhid-ups
      - UPS_PORT=auto
      - UPS_USER=
      - UPS_PASSWORD=
      - LOG=true
      - LOG_LEVEL=DEBUG
      - ENABLE_LOG_STARTUP=Y
      - LOG_WERKZEUG-true
    ports:
      - ${NUT_PORT_3493}:3493
      - ${NUT_PORT_5050}:5050
    volumes:
      - ${DOCKERCONFDIR}/nutify/nut_data:/var/run/nut
      - ${DOCKERCONFDIR}/nutify/logs:/app/nutify/logs
      - ${DOCKERCONFDIR}/nutify/instance:/app/nutify/instance
      - ${DOCKERCONFDIR}/nutify:/app/nutify
    restart: unless-stopped
    user: root        

[nutify.log](https://github.com/user-attachments/files/19171087/nutify.log)

**Comment by DartSteven** [comment]
what are these “${NUT_ENC_KEY}” did you create an .env by any chance? (because you didn't declare it in the docker-compose in case) .
Can you instead run exactly these (as per readme) and see if it works? (I just add the logs so if it doesn't work you can copy paste me)
thanks

```
services:
  nut:
    image: dartsteven/nutify:arm64-latest
    container_name: Nutify-Server
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - NUT_TYPE=SERVER
      - SERVER_NAME=UPS
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5050
      - TIMEZONE=Europe/Rome
      - ENCRYPTION_KEY=aaaa-bbbb-cccc-dddddddd-eeee-ffff-gggg
      - UPS_NAME=ups
      - UPS_DRIVER=usbhid-ups
      - UPS_PORT=auto
      - UPS_USER=admin
      - UPS_PASSWORD=hunter2
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
    ports:
      - 3493:3493
      - 5050:5050
    volumes:
      - ./nut_data:/var/run/nut
      - ./nutify/logs:/app/nutify/logs
      - ./nutify/instance:/app/nutify/instance
    restart: always
    user: root
```

(sudo) docker compose up and show the full log
