### ISSUE TITLE
Socket timeout - continuing... / Waiting for connection...

### ISSUE THREAD

**Issue by westridaz** [DartSteven/Nutify#23]
Hello,

If got 2 instances of Nutify working, if enabled logging and i see this;

2025-03-11 20:47:35,513 - web - DEBUG - ⏰ Socket timeout - continuing...
2025-03-11 20:47:35,513 - web - DEBUG - ⏳ Waiting for connection...
2025-03-11 20:47:36,260 - database - DEBUG - 📥 Buffer status before add: 35
2025-03-11 20:47:36,265 - database - DEBUG - 📥 Added data point (buffer: 36)
2025-03-11 20:47:36,265 - database - DEBUG - 📥 Buffer status after add: 36
2025-03-11 20:47:36,266 - database - DEBUG - 🕒 Current time: 2025-03-11 20:47:36.246233+01:00
2025-03-11 20:47:36,266 - database - DEBUG - ⏰ Next daily aggregation check: None

Im trying to understand wat the socket timeout  and waiting for connection means.

Running 2x Back-UPS ES 850G2 both are connected to 2 Synology NAS via USB. Synology running in vlan 40

Running 2x docker vm machines and both of them can connect to each Synology NAS. Docker machines running in vlan20

I see both of these web - DEBUG messages on the docker containers.

```
services:
  nut:
    image: dartsteven/nutify:amd64-latest
#    image: dartsteven/nutify:amd64-0.1.3Fix1Malgun
#    image: dartsteven/nutify:amd64-0.1.3TEST2Client

    container_name: nutify-server
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      # ===== SERVER CONFIGURATION =====
      - SERVER_NAME=UPS
      - SERVER_PORT=5050
      - SERVER_HOST=0.0.0.0
      - TIMEZONE=Europe/Amsterdam
      - ENCRYPTION_KEY=xxxx-xxxx-xxxx-xxxxxxx-xxxx-xxxx-xxxx
      
      # ===== UPS CONNECTION SETTINGS =====
      - NUT_TYPE=CLIENT
      - UPS_HOST=10.0.40.20   # IP/hostname of UPS [default: localhost for local USB connection]
      - UPS_NAME=ups                                    
      - UPS_DRIVER=usbhid-ups

      - UPS_PORT=auto

      - UPS_REALPOWER_NOMINAL=850
      
      # ===== UPS AUTHENTICATION =====
      - UPS_USER=monuser
      - UPS_PASSWORD=secret
            
      # ===== LOGGING CONFIGURATION =====
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
      
      # ===== DUMMY UPS CONFIGURATION =====
#      - USE_DUMMY_UPS=false
#      - DUMMY_UPS_NAME=dummy
#      - DUMMY_UPS_DRIVER=dummy-ups
#      - DUMMY_UPS_PORT=dummy
#      - DUMMY_UPS_DESC=Virtual UPS for testing
      
      # ===== SSL CONFIGURATION =====
      - SSL_ENABLED=false
      
    ports:
      - 3493:3493
      - 5050:5050
#      - 443:443
    volumes:
      - /home/andy/nut/nut_data:/var/run/nut
      - /home/andy/nut/logs:/app/nutify/logs
      - /home/andy/nut/instance:/app/nutify/instance
#      - ./ssl:/app/ssl
    restart: always
    user: root
```
