### ISSUE TITLE
No data displayed in UI

### ISSUE THREAD

**Issue by seanpdiaz** [DartSteven/Nutify#32]
Hi there I recently got this wonderful docker image spun up in my environment and am not able to get any data to show in the UI. Please let me know what can be done to get this working. Below are the files that I think you are going to need as well as a screenshot of what I see in the UI. Additionally worth mentioning I am able to confirm that the NUT server is communicating with the UPS and presenting correct information.

```yaml
services:
  nut:
    image: dartsteven/nutify:amd64-latest
    container_name: Nutify-Server
    # privileged: true
    # cap_add:
    #   - SYS_ADMIN
    #   - SYS_RAWIO
    #   - MKNOD
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb:rwm
    # device_cgroup_rules:
    #   - 'c 189:* rwm'
    environment:
      - NUT_TYPE=SERVER                           # Run full NUT server with drivers (default)
      - SERVER_NAME=Diaz-Nut
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5050
      - TIMEZONE=America/Los_Angeles
      - ENCRYPTION_KEY=pV#RF78q@0aK&R3rTgY66@q0kClzbc%MH!UW # REQUIRED: Secret key for data encryption (32+ chars)
      - UPS_HOST=10.1.19.2
      - UPS_NAME=ups
      - UPS_DRIVER=snmp-ups
      - UPS_PORT=10.1.19.2
      - UPS_USER=apc
      - UPS_PASSWORD=apc
      - SSL_ENABLED=false
     # ===== LOGGING CONFIGURATION =====
      - LOG=true                                       # Enable/disable logging (true/false)
      - LOG_LEVEL=DEBUG                                 # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
      - LOG_WERKZEUG=true                              # Enable/disable Flask's Werkzeug logs
      - ENABLE_LOG_STARTUP=Y
    ports:
      - 3493:3493
      - 5050:5050
    volumes:
      - ./nut_data:/var/run/nut
      - ./nutify/logs:/app/nutify/logs
      - ./nutify/instance:/app/nutify/instance
    restart: always
    user: root
```

Here is a photo of what I see in the UI
![Image](https://github.com/user-attachments/assets/9f31cca4-1e45-4ca2-96c9-753ba8d7059e)

Here is the output of docker logs <container id>
[nutify.log](https://github.com/user-attachments/files/19497104/nutify.log)

Here is the api.json
[ups_api_data_2025-03-28.json](https://github.com/user-attachments/files/19497109/ups_api_data_2025-03-28.json)

**Comment by DartSteven** [comment]
Why did you comment on these? 

```
    # privileged: true
    # cap_add:
    #   - SYS_ADMIN
    #   - SYS_RAWIO
    #   - MKNOD
    # devices:
    #   - /dev/bus/usb:/dev/bus/usb:rwm
    # device_cgroup_rules:
    #   - 'c 189:* rwm'
```
Try leaving them and let me know please

**Comment by seanpdiaz** [comment]
uncommented them and had the same result.

**Comment by DartSteven** [comment]
You are not the first to tell me that peanut works :)
But Peaunt is a client not a server.
Here you have to configure the server well.

Let's give it a try I don't know if it works (in the next releases I will make sure you can choose the variaples to upsc and what to see)

meanwhile can you try this? First delete everything you have or create a new directory is better and put in this docker-compose.yaml (it is in ultra beta test but just to see if anything works for you)


```
services:
  nut:
    image: dartsteven/test:amd64-TEST11
    container_name: Nut-Server
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      # ===== SERVER CONFIGURATION =====
      - SERVER_NAME=UPS
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5050
      - TIMEZONE=Europe/Rome
      - ENCRYPTION_KEY=aaaa-bbbb-icky-fzwratjz-qvpy-icky-fzwr
      - UPS_NAME=ups

      # ===== UPS CONNECTION SETTINGS =====
      - UPS_DRIVER=usbhid-ups
      - UPS_PORT=auto
      - UPS_USER=admin
      - UPS_PASSWORD=hunter2
      - SSL_ENABLED=true
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    volumes:
      - ./nut_data:/var/run/nut
      - ./etc:/etc/nut
      - ./nutify/logs:/app/nutify/logs
      - ./nutify/instance:/app/nutify/instance
      - ./ssl:/app/ssl
    restart: always
    user: root
```

**Comment by seanpdiaz** [comment]
Okay so with that docker image it does now work however I did have to adapt it a little bit since I am using a network UPS. One thing worth noting is that the documentation for configuring a network UPS using SNMP is actually incorrect based on your current code.

The issue surrounding SNMP not working appears to come from your "src/generate-settings.sh" file specifically on line 321 where you are creating the config file for ups.conf. As you can see below you are using "UPS_PORT" instead of "UPS_HOST" as mentioned in the documentation. Not sure if the actual error here lies in the code or the documentation but the workaround was to set "UPS_PORT" equal to the ip address of my UPS.


```shell
# ---- GENERATING NUT CONFIGURATION FILES ----

# 1. Generate ups.conf
UPS_CONF_CONTENT=$(cat << EOF
[${UPS_NAME:-ups}]
    driver = ${UPS_DRIVER:-usbhid-ups}
    port = ${UPS_PORT:-auto}
    pollinterval = 1
    pollfreq = 1
    desc = "UPS ${SERVER_NAME:-Nutify}"
    # Additional permissions options for USB drivers
    user = nut
    group = nut
    # Debug options for USB issues
    # Uncomment the next line for more verbose debugging
    # debug_min = 1
EOF
)
```

Here is what is seen in the documentation versus what it should say based on the current code.
> Usage: Set UPS_DRIVER=snmp-ups and UPS_HOST=ip_of_your_ups in your docker-compose.yaml

which is incorrect, and should be as below based on the current code.

> Usage: Set UPS_DRIVER=snmp-ups and UPS_PORT=ip_of_your_ups in your docker-compose.yaml

Below is my working docker-compose.yml file.

```yaml
services:
  nut:
    image: dartsteven/test:amd64-TEST11
    container_name: Nut-Server
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      # ===== SERVER CONFIGURATION =====
      - SERVER_NAME=UPS
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5050
      - TIMEZONE=America/Los_Angeles
      - ENCRYPTION_KEY=pV#RF78q@0aK&R3rTgY66@q0kClzbc%MH!UW

      # ===== UPS CONNECTION SETTINGS =====
      - UPS_NAME=ups
      - UPS_DRIVER=snmp-ups
      - UPS_PORT=10.1.19.2
      - UPS_USER=apc
      - UPS_PASSWORD=apc
      - SSL_ENABLED=false
      # ===== LOGGING CONFIGURATION =====
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    volumes:
      - ./nut_data:/var/run/nut
      - ./etc:/etc/nut
      - ./nutify/logs:/app/nutify/logs
      - ./nutify/instance:/app/nutify/instance
      - ./ssl:/app/ssl
    restart: always
    user: root
```

![Image](https://github.com/user-attachments/assets/7f70906d-13c1-4265-b7de-3c799f187c52)
