### ISSUE TITLE
Multi UPS units?

### ISSUE THREAD

**Issue by lars18th** [DartSteven/Nutify#7]
Hi @DartSteven ,

This project support multiple UPS units?

In my home I've three UPS. One is connected to my PC workstation, and two are daisy chained for my NUC cluster. The idea is to support "complex" UPS configurations. It's this supported?

Regards and nice project!

**Comment by DartSteven** [comment]
This is definitely something I will implement. But first I would like to make the project stable enough and implement a notification system in addition to email (I wanted to start with ntfy).
I also have two ups at home and it is convenient for me to have one interface for everything :)

**Comment by DartSteven** [comment]
https://github.com/DartSteven/Nutify/discussions/46

**Comment by taylormia** [comment]
@DartSteven Great job on this !! I have two APC Smart-UPS connected via USB to my docker host. Do you recommend running a separate instance of Nutify on the host for each UPS? That is, until you come up with a single instance that can support more than one directly connected UPS.

**Comment by DartSteven** [comment]
> [@DartSteven](https://github.com/DartSteven) Great job on this !! I have two APC Smart-UPS connected via USB to my docker host. Do you recommend running a separate instance of Nutify on the host for each UPS? That is, until you come up with a single instance that can support more than one directly connected UPS.

Hi! thanks for the compliments, it's always nice :)
For the moment Nutify is thought as a single instance and the database is also configured and thought as a single instance, you'd better create two separate docker-compose. In the near future (when all the bugs are over) I will be doing multi ups :) read here : https://github.com/DartSteven/Nutify/discussions/46

**Comment by taylormia** [comment]
@DartSteven I configured the first instance successfully and it finds the first UPS on Bus 3, Device 3, but getting a "Failed to start UPS drivers" error on the second instance which is on Bus 3, Device 4. I have tried specifying the devices parameter as default as well as the two options below with same error.
- /dev/bus/usb/003:/dev/bus/usb/003:rwm  - **and** - /dev/bus/usb/003/004:/dev/bus/usb/003/004:rwm

![Image](https://github.com/user-attachments/assets/f324b622-bd72-4f03-83b6-d310ff2079e7)

Here is my `lsusb` output:
![Image](https://github.com/user-attachments/assets/bdfe2dcf-90fb-463f-926f-99f2c6577781)

Any ideas? Thank you.

**Comment by DartSteven** [comment]
I need to see both of your docker composer, and know if you are in vm, in docker and on which os.

**Comment by taylormia** [comment]
I'm on Ubuntu 22.04.5 LTS, Docker 28.1.1, Docker Compose 2.35.1, Portainer CE 2.21.4
Here are the compose files and the scenarios:

When I have both UPS connected at the same time and start both containers one after the other - one loads successfully and the other does not with the errors above.
If I have only one UPS plugged in and start one container - it loads successfully. Then if I plug in the second UPS and start the second container - it also loads successfully.
I have tested both UPS and containers interchangeably in this scenario with the above results.

It seems that I cannot have both UPS plugged in at the same time and then start each container one after the other. This would be a problem if I rebooted the docker host and not have one UPS unplugged when the containers started.

Thanks for your help.

**UPS0: Bus 003 Device 003**

```
services:
  nut:
    image: dartsteven/nutify:amd64-0.1.5
    container_name: nutify-ups0
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - NUT_TYPE=SERVER   # Run full NUT server with drivers (default)
      - SERVER_NAME=UPS0
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5050
      - TIMEZONE=America/Chicago
      - ENCRYPTION_KEY=ahgt-bnhy-cvbg-dlkfghju-efty-fjkl-gnmk   # REQUIRED: Secret key for data encryption (32+ chars)
      - UPS_NAME=ups0
      - UPS_DRIVER=usbhid-ups
      - UPS_PORT=auto
      - UPS_USER=admin
      - UPS_PASSWORD=password
    ports:
      - 3493:3493
      - 5050:5050
    volumes:
      - /home/user/apps/nutify/nutify0_data:/var/run/nut
      - /home/user/apps/nutify/nutify0_logs:/app/nutify/logs
      - /home/user/apps/nutify/nutify0_instance:/app/nutify/instance
    restart: unless-stopped
    user: root
```

**UPS1: Bus 003 Device 004** 

```
services:
  nut:
    image: dartsteven/nutify:amd64-0.1.5
    container_name: nutify-ups1
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - NUT_TYPE=SERVER  # Run full NUT server with drivers (default)
      - SERVER_NAME=UPS1
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5050
      - TIMEZONE=America/Chicago
      - ENCRYPTION_KEY=ahgt-bnhy-cvbg-dlkfghju-efty-fjkl-gnml # REQUIRED: Secret key for data encryption (32+ chars)
      - UPS_NAME=ups1
      - UPS_DRIVER=usbhid-ups
      - UPS_PORT=auto
      - UPS_USER=admin
      - UPS_PASSWORD=password
    ports:
      - 3494:3493
      - 5051:5050
    volumes:
      - /home/user/apps/nutify/nutify1_data:/var/run/nut
      - /home/user/apps/nutify/nutify1_logs:/app/nutify/logs
      - /home/user/apps/nutify/nutify1_instance:/app/nutify/instance
    restart: unless-stopped
    user: root
```

**Comment by DartSteven** [comment]
in both you put the generic - /dev/bus/usb:/dev/bus/usb:rwm
did you try to put just the correct bus different for each dockercompose?

**Comment by taylormia** [comment]
yes, i have used the specific bus id in each compose file with the same results

**Comment by DartSteven** [comment]
Try whit this : 

dartsteven/test:amd64-0.1.6TEST5

and use exactly this docker compose (except for usb) if it still doesn't work come on Discord and as soon as I have 10 minutes free let's see what can be done


```
services:
  nut:
    image: dartsteven/test:amd64-0.1.6TEST5
    container_name: Nutify
    privileged: true
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - MKNOD
    devices:
      - /dev/bus/usb:/dev/bus/usb:rwm
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      # ===== SERVER CONFIGURATION =====
      - SERVER_PORT=5050
      - SERVER_HOST=0.0.0.0
      # ===== LOGGING CONFIGURATION =====
      - LOG=true
      - LOG_LEVEL=DEBUG
      - LOG_WERKZEUG=true
      - ENABLE_LOG_STARTUP=Y
      - SSL_ENABLED=false
      - SECRET_KEY=test1234567890 # for password encryption and decryption in the database
    ports:
      - 3493:3493
      - 5050:5050
      - 443:443
    volumes:
      - ./Nutify_volumes/logs:/app/nutify/logs
      - ./Nutify_volumes/instance:/app/nutify/instance
      - ./Nutify_volumes/ssl:/app/ssl
      - ./Nutify_volumes/etc/nut:/etc/nut
    restart: always
    user: root
```
